module.exports = {
    products: [
        {
            id: '1',
            name: 'Slim Shirt',
            category: 'Tops',
            image: 'assets/slim.jpg',
            price: 120,
            climate: 'hot',
            style: 'tank',
            color: 'white',
            material: 'cotton',
            cart: false,
            size: 'S',
            numInStock: 8
        },
        {
            id: '2',
            name: 'V-Neck',
            category: 'Tops',
            image: 'assets/v-neck.jpg',
            price: 140,
            climate: 'hot',
            style: 'tank',
            color: 'white',
            material: 'wool',
            cart: false,
            size: 'XL',
            numInStock: 0
        },
        {
            id: '3',
            name: 'Tapered Pants',
            category: 'Pants',
            image: 'assets/tapered.jpg',
            price: 120,
            climate: 'hot',
            style: 'tank',
            color: 'white',
            material: 'cotton',
            cart: false,
            size: 'M',
            numInStock: 6
        },
        {
            id: '4',
            name: 'Bucket Hat',
            category: 'Headwear',
            image: 'assets/bucket-hat.jpg',
            price: 80,
            climate: 'hot',
            style: 'tank',
            color: 'white',
            material: 'cotton',
            cart: false,
            size: 'L',
            numInStock: 20
        },
        {
            id: '5',
            name: 'Golfer',
            category: 'Tops',
            image: 'assets/golfer.jpg',
            price: 140,
            climate: 'hot',
            style: 'tank',
            color: 'white',
            material: 'silk',
            cart: false,
            size: 'M',
            numInStock: 0
        },
        {
            id: '6',
            name: 'Shorts',
            category: 'Pants',
            image: 'assets/shorts.jpg',
            price: 60,
            climate: 'hot',
            style: 'tank',
            color: 'white',
            material: 'cotton',
            cart: false,
            size: 'S',
            numInStock: 1
        },
        {
            id: '7',
            name: 'Beanie',
            category: 'Headwear',
            image: 'assets/beanie.jpg',
            price: 60,
            climate: 'hot',
            style: 'tank',
            color: 'white',
            material: 'wool',
            cart: false,
            size: 'M',
            numInStock: 15
        },
        {
            id: '8',
            name: 'Hoodie',
            category: 'Tops',
            image: 'assets/hoodie.jpg',
            price: 120,
            climate: 'hot',
            style: 'tank',
            color: 'white',
            material: 'cotton',
            cart: false,
            size: 'XL',
            numInStock: 8
        }
    ]
}